# Qual é o número de processos por situação da decisão final no acervo de cada ministro? {#sec-decisaofinal}

A seguinte análise tem como objetivo evidenciar as proporções das duas possíveis situações de decisão final dos processos para cada ministro. Nota-se que a variável "Situação da decisão final"(variável categórica) possui duas categorias: "Com decisão final" ou "Sem decisão final". Além disso, evidencia-se que 1142 processos não possuem seus ministros identificados. Dessa maneira, estes foram excluídos da análise.

```{r}
#| label: fig-situacao-processos-ministros
#| fig-cap: "Gráfico de coluna bivariado dos ministros e a situação final do processo"

source("~/Documents/Atividade do PS - STF/rdocs/analises.R")

g4<- ggplot(situacao_final_por_ministro) +
  aes(
    x = fct_reorder(Relator, Quantidade, .desc = T),
    y = Quantidade,
    fill = `Situação da decisão final`,
    text = paste("Relator:", Relator, 
                   "<br>Quantidade:", Quantidade, 
                   "<br>Frequência:", percent(Frequencia))
  ) +
  geom_col(position = position_dodge2(preserve = "single", padding = 0)) +
  scale_fill_manual(values = c("Com decisão final" = "#3a445d", "Sem decisão final" = "#DC758F"))+
  coord_flip() +
  theme_bw() +
  labs(y = "Quantidade", x = "", fill = "Situação da decisão final")

ggplotly(g4, tooltip = "text") %>%
  layout(
    height = 800,  
    yaxis = list(
      autorange = "reversed",  
      tickangle = 0,
      tickfont = list(size = 10),
      fixedrange = FALSE 
    )
  )
```

Através da @fig-situacao-processos-ministros, nota-se que todos os ministros possuem maior quantidade de processos com decisão final do que sem decisão. O ministro com maior porcentagem de processos desta forma é o Ministro Presidente seguido do Ministro Ricardo Lewandowski e o Ministro Flávio Dino.

Em termos de quantidade bruta de processos com decisão final, nota-se que o Ministro Presidente está em primeiro lugar seguido dos ministros Alexandre de Moraes e Nunes Marques.

Do outro lado, os ministros Luís Roberto Barroso, Marco Aurélio e André Mendonça são os ministros com maior frequência relativa de processos sem decisão final, respectivamente. Evidencia-se também que o ministro André Mendonça é o ministro com maior quantidade absoluta de processos sem essa decisão.
